[package]
name = "mh-cli"
version = "1.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Command-line tools for magazine-core"

[[bin]]
name = "mh"
path = "src/main.rs"

[[bin]]
name = "mh-ui-ext"
path = "src/ui_ext_main.rs"

[dependencies]
getrandom = "0.2"
mh-db = { workspace = true }
mh-host = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
mh-domain = { workspace = true }
