//! Verifies the Rust framing produces byte-identical frames to the pinned
//! `golden/*.hex` fixtures (generated by the independent Python oracle).
//! This is the cross-implementation conformance gate (CONTRACT §9).

use std::fs;
use std::path::Path;

#[test]
fn golden_vectors_match_pinned_fixtures() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("golden");
    for (name, msg) in mh_protocol::golden::messages() {
        let expected = fs::read_to_string(dir.join(format!("{name}.hex")))
            .unwrap_or_else(|e| panic!("missing fixture {name}.hex: {e}"))
            .trim()
            .to_string();
        let actual = mh_protocol::golden::frame_hex(&msg);
        assert_eq!(actual, expected, "golden frame mismatch for {name}");
    }
}
